#!/bin/bash

arr=(
LOGIN.TITLE
LOGIN.PLACEHOLDER
LOGIN.SUBMIT
LOGIN.ERROR.REQUIRED_FIELD
LOGIN.ERROR.INVALID_PASSWORD
LOGIN.ATTENTION
LOGIN.RIGHT_PASSWORD
LOGIN.FIVE_ATTEMPTS
LOGIN.ANY_PROBLEM
HOME.AVERAGE_TIME
HOME.MINUTE_SUFFIX
HOME.AT
HOME.UNTIL
HOME.VOICE
HOME.LANG
HOME.CALLING
LAB_TOKEN_CAROUSEL.TITLE
LAB_TOKEN_CAROUSEL.STATUS.UNDER_REVIEW
LAB_TOKEN_CAROUSEL.STATUS.IN_REPAIR
LAB_TOKEN_CAROUSEL.STATUS.FINISHING
LAB_TOKEN_CAROUSEL.DISCLAIMER
LAB_TOKEN_CAROUSEL.CALCULATING
LAB_TOKEN_CAROUSEL.LATE
NEXT_TOKENS_QUEUES.TITLE.HEAD
NEXT_TOKENS_QUEUES.TITLE.TAIL
SCL1.NO_TOKEN_REGISTERED
SCL1.NEXT_TOKENS_QUEUES.TITLE.HEAD
SCL1.NEXT_TOKENS_QUEUES.TITLE.TAIL
SCL1.WAIT_TOKEN_CALL
SCL1.VIDEO_DIALOG.TITLE
SCL1.VIDEO_DIALOG.DESCRIPTION
SCL1.VIDEO_DIALOG.DRAG_AND_DROP_DESCRIPTION
SCL1.VIDEO_DIALOG.BUTTON_SELECT
SCL1.VIDEO_DIALOG.BUTTON_CLOSE
SCL1.VIDEO_DIALOG.REMARKS
SCL1.VIDEO_DIALOG.REMARK_VIDEO_TYPE
SCL1.VIDEO_DIALOG.REMARK_SINGLE_FILE_SIZE
SCL1.VIDEO_DIALOG.REMARK_TOTAL_FILE
SCL1.VIDEO_DIALOG.ERROR_MESSAGE_GENERAL
SCL1.VIDEO_DIALOG.ERROR_MESSAGE_VIDEO_TYPE
SCL1.VIDEO_DIALOG.ERROR_MESSAGE_SINGLE_FILE_SIZE
SCL1.VIDEO_DIALOG.ERROR_MESSAGE_TOTAL_FILE_SIZE
SCL1.VIDEO_DIALOG.ERROR_MESSAGE_TOTAL_FILES
SCL1.VIDEO_DIALOG.ERROR_MESSAGE_VIDEO_PLAYER
SCL1.VIDEO_DIALOG.ERROR_MESSAGE_VIDEO_CAN_NOT_PLAY
)
#arr=(`< arq.txt`)
#echo "${arr[@]}"

if [ -f not_used.txt ] 
then
  rm not_used.txt
fi

for i in `echo ${arr[*]}`; do
    #cd ~/dev/workspace/qless/qless-asc/code/client/admin
    #cd ~/dev/workspace/qless/qless-asc/code/client/attendants
    #cd ~/dev/workspace/qless/qless-asc/code/client/smart-queues
    #cd ~/dev/workspace/qless/qless-asc/code/client/totem
    cd ~/dev/workspace/qless/qless-asc/code/client/tv

    grep -r -l -w $i

    if [ ! $? -eq 0 ]
    then
        cd ~/scripts
        echo $i>>not_used.txt
    fi 
done